### PR TITLE
adding two gt-sets hosted on zenodo

### PR DESCRIPTION
**Pull request by thodel**
Scholarly edition of Königsfelden (Middle Ages & Early Modern) and Urfehdebuch from Basel (Early Modern)

### CODE REVIEW

**Comment by alix-tz** [comment]
Hello Tobias,

Thank you very much for this contributions!

Just checking: you don't have any author to indicate for `urfehdebuch-htr.yml`?

**Comment by thodel** [comment]
Hi Alix

Yes, the author indication for the data is quite difficult.
The page xml have been prepared by David Schoch, Peter Dängeli and myself.
The edition is by Susanna Burghartz, Sonia Calvi and Georg Vogeler
Transcribers were: Laila Baur, Benedikt Egli, Gabriela Gehrig, Alexandra Isabelle Heini, Rosanna Rossi, Benjamin Siegrist, Remo Wasmer, Lynn Zimmermann

Don’t know, if this should all be represented.

Thanks a lot and best wishes,

Tobias
Am 20. März 2022, 20:44 +0100 schrieb Alix Chagué ***@***.***>:

**Comment by PonteIneptique** [comment]
We could help format this ;)

**Comment by PonteIneptique** [comment]
I'll do that in the next days, as well as augment some of the metrics through HUMG if @thodel is OK :)

**Comment by thodel** [comment]
Thanks, added the missing contributors in the attached file (upload of yml seems not possible here :-)
[urfehdebuch-htr.txt](https://github.com/HTR-United/htr-united/files/8345190/urfehdebuch-htr.txt)

**Comment by PonteIneptique** [comment]
Thanks for everything @thodel !

**Pull request merged**
