### PR TITLE
Create fondue-gasparosarditoponomasia-dataset.yml

### PR DESCRIPTION
**Pull request by PaulineJac**
Hello, 

I have created a pull request to post the HTR data of my project. Could you please accept it. 
Thank you very much.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
@alix-tz @PaulineJac This repository has no images nor does it seems to provide a script to download them. What should be our approach then ?

**Comment by PaulineJac** [comment]
> 
Hello, I am sorry, I'm travelling, and I have network cuts... I cannot publish the images, but I can transmit them on demand to researchers who need them: I will indicate this in a Readme.

**Comment by PonteIneptique** [comment]
Please indicate it in the description of the dataset as well :) Thanks!

**Review by PaulineJac — COMMENTED** [review]
add e-mail adresse for images request.

**Pull request merged**
