### PR TITLE
Create joseph-hooker-htr.yml

### PR DESCRIPTION
**Pull request by alix-tz**
Modification following #119 to add the Joseph Hooker HTR dataset.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Can we actually have a folder `single-datasets` for situation like these, except if you have information about the context I don't have ?

**Comment by alix-tz** [comment]
You mean in stead of creating a "josephe-hooker-correspondance-project" folder?

**Comment by PonteIneptique** [comment]
Yup

**Comment by alix-tz** [comment]
So, in cases like this, I use the information in the "projec-name" field.

**Comment by alix-tz** [comment]
Alright, after import in eScriptorium, it looks all good!

**Pull request merged**
