### PR TITLE
Create dataset-for-late-medieval-castilian-text-recognition.yml

### PR DESCRIPTION
**Pull request by matgille**
I'm adding my phd dissertation corpus here (in-domain and out-of-domain)

= )

### CODE REVIEW

**Comment by matgille** [comment]
This dataset contains the incunabula dataset I've already published here some time ago. I'm removing it.

**Comment by matgille** [comment]
I'm waiting for the acceptation and the final version of the paper to publish the data on htr united.

**Comment by PonteIneptique** [comment]
:'(

**Comment by matgille** [comment]
The article has been amended, the v2 is being reviewed, and it will be published soon (hopefully). Let's publish if the metadata is OK = )

**Comment by PonteIneptique** [comment]
@alix-tz We need to decide on this one what to do. This is the first deletion of a previous dataset. I am a bit skeptical about removing a previously registered dataset personally, but I'd like to have your opinion.

**Comment by alix-tz** [comment]
> @alix-tz We need to decide on this one what to do. This is the first deletion of a previous dataset. I am a bit skeptical about removing a previously registered dataset personally, but I'd like to have your opinion.

In deed, it opens a pandora box, but at the same time, I understand that some situations may justify it (like similar to retracting a publication). 

@matgille I'm not sure I understand why you removed the previous dataset. Was it because the dataset is contained in the newer dataset? Can you explain?

**Comment by PonteIneptique** [comment]
Nope, I will think we need a better way to deal with this.
We'll talk about with Alix off GitHub because this is a larger problem.

**Comment by PonteIneptique** [comment]
The catalog being versioned, we are gonna include this change. We'll have to show the version of the catalog so that it is really used...

**Pull request merged**
