### PR TITLE
Create fondue-kunsthistorisches-uzh-archivdatenbank.yml

### PR DESCRIPTION
**Pull request by PaulineJac**
Hello ! 
I hope you had a very pleasant end of year celebration 🎉. 
Could you include this dataset in your catalogue?  
Thank you very much. 
Pauline

### CODE REVIEW

**Comment by alix-tz** [comment]
Hello ! 

Thank you for this submission! I see 1 invalid field in the form for "project-website:" (you put "Genève") but it should be a URL to a website dedicated to the project. 

And, a memo for us before merging, surname and name need to be swapped (cf. #95) ⚠️

**Comment by alix-tz** [comment]
@PonteIneptique don't we test the validity of the value in "project-website" (like it should look like a URL)? I'm surprised that the HTRUC validation passed 🤔

**Comment by PaulineJac** [comment]
Sorry for the website mistake .... I made the change!

**Comment by PaulineJac** [comment]
Done 😅 !

**Comment by alix-tz** [comment]
Then it's all good! Thank you for your contribution to HTR-United! (the dataset and the feedback! :D)

**Comment by PonteIneptique** [comment]
Congrats for being our ticket number 100 !

**Pull request merged**
