### PR TITLE
Create bullinger-htr-dataset.yml

### PR DESCRIPTION
**Pull request by pstroe**
integration of new dataset

### CODE REVIEW

**Comment by alix-tz** [comment]
Hello! It looks all good to me as far as the description is concerned, however, I tried taking a look at your data (via Zenodo) and it seems that the .zip files are empty. Could you check that your files are correct?

**Comment by pstroe** [comment]
hi alix,
the github repo is pretty big (50gb), and i just enabled synching with github on zenodo, so i don't think it will all be loaded on zenodo. do you think a remark in the readme concerning the download (only possible via github lfs) would solve the issue?

**Comment by alix-tz** [comment]
Even 50Go is big for Github to be honest, but yes, you should definitely mention it somewhere, otherwise people might think the dataset is not usable. I was initially trying to download the zip files individually from Github but it was just loading endlessly, that's why I switched to Zenodo.

If I may, I would also recommend offering a small zip file as a sort of preview, with maybe 5 images and the corresponding XML files to allow people to download them and try to the dataset before downloading the whole 50Go if it does correspond to what they want.

**Comment by PonteIneptique** [comment]
Hi both,
I would just like to add that it is possible to edit automatic upload to add files manually: it might be something to look into if the automatic linking between Zenodo and Github did not work :)

**Comment by pstroe** [comment]
thanks you both for your suggestions. i will upload a small sample of the training data tomorrow. 
the images are only available from our servers (they are preprocessed and, so to speak, ready to use). external storage would be possible, i guess, but it will again take time to set up.

**Comment by pstroe** [comment]
any updates? :-)

**Comment by PonteIneptique** [comment]
@alix-tz has this PR for her, but the sheer mass of text has been a tough one to review. This is still on her plate (but she's on vacation today if I am not mistaken).
We did not forget you ;)

**Comment by PonteIneptique** [comment]
Ok, we finally got to it, welcome to Bullinger :)

**Pull request merged**
