### PR TITLE
Adding datasets created during the HTR Winter School 2022.

### PR DESCRIPTION
**Pull request by hajicj**
During the [HTR Winter School 2022 at the Austrian Academy of Sciences](https://www.oeaw.ac.at/imafo/veranstaltungen/detail/introduction-into-handwritten-text-recognition-1), four new datasets were created and uploaded to Zenodo.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Thanks for proposing all those datasets and welcome on the platform :)

**Comment by PonteIneptique** [comment]
I should have asked before merging: I'd prefer, for cataloging reasons, to merge projects under the HTR Winter School 2022 - OEAW rather than 4 different projects. Would you be okay with this ?

**Comment by hajicj** [comment]
I'm not sure it's a good idea -- these are really four completely different datasets, on different languages, with different transcription guidelines, etc. The fact they were all created during the same winter school is misleading rather than helpful. But, thinking about this, the folder names are just as misleading. Maybe the right solution would actually be to rename the folders to not involve the HTR Winter School name?

**Comment by PonteIneptique** [comment]
I do not think this discards using project: it actually help groups things together, find data that were created at the same time, in the same context, but which might vary. It could be Project, Event, Course, etc. It's more of a useful way to find things than anything else.

However, if you think these should not be grouped, we can simply remove the project line: it's not mandatory.

**Comment by ciceronianus** [comment]
Hi :), I am one of the organizers of the HTR Winter School. As @hajicj pointed out, these are 4 datasets that represent 4 very different sources: medieval Czech, medieval German, Late Latin and Carolingian Latin. Also each of these datasets was prepared by another group and with different transcription rules, hence I would prefer to have them separated. :)

**Comment by PonteIneptique** [comment]
Thanks @ciceronianus. Then I'll remove project tagging altogether for these :)

**Comment by ciceronianus** [comment]
Just saying that they should be 4 datasets, with 4 different descriptions. :) I hope I haven't misunderstood you! If there is a way to link the four without making them one project with one description, I would be completely fine with that. :)

**Comment by PonteIneptique** [comment]
It would be only a linking category (Project), which still differentiates each dataset (each dataset has its own desc, own title but is linked to the others through a project, HTR Winter School Austrian Academy of Sciences 2022).
If you are ok with this, then let's go with this :)

**Comment by ciceronianus** [comment]
Oh, got it! Sorry for misunderstanding :). If each dataset is still findable and has its own description, then that sounds fine to me!

**Comment by ciceronianus** [comment]
Hmm, maybe the best would be simply "HTR Winter School 2022". There were quite a lot of institutions participating :) (Austrian Academy of Sciences and Princeton as the main institutionshj, but also University of Bielefeld, Czech Academy of Sciences, University of Vienna etc.). If a specification is needed / desired, we can discuss it :).

**Comment by PonteIneptique** [comment]
I think adding a little more details would be a safe bet: there might be other winter schools coming our way (Maybe not, but then maybe next year, under a different tutelage)

**Comment by ciceronianus** [comment]
Yeah, you are right...  I just don't want to omit somebody. :/ Hmm... Mybe then HTR Winter School 2022 (Institute for Medieval Research of the Austrian Academy of Sciences + MARBAS, Princeton University at al.)? Or I guess it is too long?

**Comment by ciceronianus** [comment]
Or if there is no space, then your suggestion with added "et al." would be probably fine as well in order to indicate that this was a large collaborative effort. I can then add a general description of the project.

**Comment by PonteIneptique** [comment]
Might be quite long... Can I recommend `Vienna HTR Winter School 2022`, focusing on the place rather than the paying institution ?

**Comment by ciceronianus** [comment]
The issue is that a big part of our HTR School was actually virtual (4 virtual sessions). But maybe "HTR Winter School 2022, Vienna" is fine.

**Comment by PonteIneptique** [comment]
Then here we go :)

**Pull request merged**
